### PR TITLE
Initial implementation of feBlend and feFlood

### PR DESCRIPTION
**Pull request by mrbean-bremen**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
I will resolve the conflicts later.

**Comment by mrbean-bremen** [comment]
@jonstelly: please check if there is something missing with respect to your own changes mentioned in #496.

**Comment by jonstelly** [comment]
That looks good, only see two things:

[SvgBlendMode has several other options](https://github.com/Kymeric/SVG/commit/89d5e7f9d4a787ff9a7c0b707d9d5696d8574589#diff-6d83bf45faed77dbf6526d6089f96f76)

And then the [converter](https://github.com/Kymeric/SVG/commit/89d5e7f9d4a787ff9a7c0b707d9d5696d8574589#diff-f22bb9959b38260d35e93814c2b4107b) that uses [dashed lower case](https://github.com/Kymeric/SVG/commit/89d5e7f9d4a787ff9a7c0b707d9d5696d8574589#diff-30c217277fc273a5c17191e7a55af712)

**Comment by mrbean-bremen** [comment]
> SvgBlendMode has several other options

Ah, you are using a newer spec. I used SVG 1.1, which is the one (partly) implemented in SVG.NET. There are no attributes with dashes in that one. It may make sense to use the newer ones... I will see if I can add them.

I'm a bit unsure if I shall merge this, as the implementation is not complete and has some problems (like fuzzy edges) - OTOH, it would give somebody else the possibility for improvements.

**Comment by jonstelly** [comment]
Ah, I didn't even realize I had pulled those from a newer version.

And I agree, it would be nice to merge this so others could pick it up from there but there's not really a great mechanism for marking something as experimental...

My personal opinion: It would have been nice if this library was split into a document library and a separate rendering library.  That would make the argument easier for merging something that helps document 'completeness' even if it couldn't be rendered, then an issue could be opened against the rendering library to add support.  I think this pull request is valuable enough on that front to merge it, but I can appreciate the argument against that.

If you're uncomfortable merging it to master, maybe you could merge it into a new branch to get it into this repository and make it easier for others to complete?  That doesn't help people working with NuGet packages but it may make it easy enough that someone picks it up to finish things.

**Comment by mrbean-bremen** [comment]
Ok, I incorporated your changes into the PR. Did a bit of rebasing, so that one commit has your changes, and the second one my changes on top of that. I did not start to implement the rest of the SVG 2 modes, but this can be done later by anyone.
Regarding merging - I'm going a bit back and forth with this one. I already had it merged, but backed it out again. 
Generally, I have no good experience with long-living feature branches with large changes, and I tend more to an incremental approach in development. So from my perspective, merging could be ok if indicating in the release notes that this feature is experimental (and there is an open issue for filters anyway), but I leave that decision to @tebjan.
@tebjan - what do you think?

**Comment by mrbean-bremen** [comment]
> My personal opinion: It would have been nice if this library was split into a document library and a separate rendering library

That would have been a good idea if done from start, and still may be, though it would need a major refactoring now. As I understand it, the primary intention for creating this library by Microsoft was to provide SVG rendering support for web pages, which IE lacked at that time - so this probably wasn't something they had in mind.

**Comment by mrbean-bremen** [comment]
Closing this in favor of #641.
@wieslawsoltes - you can check if something is useable here for you, but I never got to really finish/fix this.

**Comment by wieslawsoltes** [comment]
> Closing this in favor of #641.
> @wieslawsoltes - you can check if something is useable here for you, but I never got to really finish/fix this.

@mrbean-bremen I will see what can be reused in my PR

**Pull request closed without merging**
