### PR TITLE
Add Property to Disable Dtd Processing

### PR DESCRIPTION
**Pull request by inforithmics**
Disable Dtd Processing, is not necessary.
1. Xml is not validated.
2. some svg's don't have a dtd
3. Designed Svgs have a dtd, this causes to parse the dtd which takes a long time.

#### What does this implement/fix? Explain your changes.
Performance improvement

image

Here the Read of SvgTextReader takes 2.2 sec the reason is that the dtds are parsed but not needed 
This pull request reduces this to almos 0

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
I would make this a static flag on SvgDocument
```C#
public static bool DisableDtdProcessing { get; set; } = true;
```

**Comment by inforithmics** [comment]
> I would make this a static flag on SvgDocument
> 
> ```cs
> public static bool DisableDtdProcessing { get; set; }
> ```

Good idea, because it seems it is needed.

**Comment by wieslawsoltes** [comment]
Looking good.

**Comment by wieslawsoltes** [comment]
@inforithmics I would add also:
```C#
XmlResolver = SvgDocument.DisableDtdProcessing ? new XmlUrlResolver() : new SvgDtdResolver(),
```

**Review by mrbean-bremen — APPROVED** [review]
@wieslawsoltes - this looks good to me, I would merge it now, if you don't mind.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes - this looks good to me, I would merge it now, if you don't mind.

Go ahead look good.

**Pull request merged**
