### PR TITLE
Compatibility: Ignore textLength attribute if X attribute is list.

### PR DESCRIPTION
**Pull request by H1Gdev**
### Sample SVG
```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="80" height="80" xml:space="preserve">
<text x="10,30,50"            y="15" fill="#000" font-size="14"                >ABC</text>
<text x="10,30,50"            y="30" fill="#000" font-size="14" textLength="14">ABC</text>
<text x="10,30,50" dx="4,4,4" y="45" fill="#000" font-size="14" textLength="14">ABC</text>
<text x="10"                  y="60" fill="#000" font-size="14" textLength="14">ABC</text>
<text                         y="75" fill="#000" font-size="14" textLength="14">ABC</text>
</svg>
```

#### Chrome
chrome

#### FireFox
firefox

### Actual
output_before

### Fixed
output_after

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Same here - if you could add the test files...

**Comment by H1Gdev** [comment]
@mrbean-bremen 

When will these PRs be released to NuGet ?

**Comment by mrbean-bremen** [comment]
This is something @tebjan has to decide - there is also a [new issue](https://github.com/vvvv/SVG/issues/382) with this question, you may comment there.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

Thanks!

**Pull request merged**
