### PR TITLE
Added documentation generation using docfx

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- added generated API doc
- added documentation from Wiki

This is a first try at generating GitHub Pages documentation. I added generated API doc, and copied the Wiki pages over.
This currently only works in my branch due to permission issues.

@tebjan - to get this to work in master, you need to generate a personal GitHub access token with public repo access (GitHub settings / Developer settings / Personal access tokens), encrypt it using [Appveyor](https://ci.appveyor.com/tools/encrypt), and replace the current token in appveyor.yml.
You also may have to enable GitHub pages on the repository settings site (options page, scroll down to GitHub Pages, and select "gh-pages branch").

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Ah, and the created page is [here](https://mrbean-bremen.github.io/SVG/).

**Comment by gvheertum** [comment]
Looking great!

**Comment by mrbean-bremen** [comment]
ping @tebjan

**Comment by mrbean-bremen** [comment]
@tebjan - if you could enable gh-pages on the project (see original comment), we could at least update the documentation manually, even without the automatic stuff.

**Comment by tebjan** [comment]
@mrbean-bremen GitHub Pages is on and the source is configured as gh-pages branch. other options are master or the /docs folder on master. options are explained here: https://help.github.com/en/articles/configuring-a-publishing-source-for-your-github-pages-site
let me know what would work best.

**Comment by mrbean-bremen** [comment]
@tebjan - thanks! That is actually what I meant, though I would have expected the page showing up, as there is already a valid [gh-pages branch](https://github.com/vvvv/SVG/tree/gh-pages). The site should be [here](https://vvvv.github.io/SVG/), but something seems to be still wrong. Could you check on the settings site if this is the correct URL?

**Comment by mrbean-bremen** [comment]
At the settings page for my fork, it states: 
```Your site is published at https://mrbean-bremen.github.io/SVG/```
so I would expect a similar entry in the settings for the main repo.

**Comment by tebjan** [comment]
yes indeed, somehow it didn't get the trigger from the new branch, i had to switch to another source and then back to gh-pages branch. now it works: http://vvvv.github.io/SVG/

**Comment by mrbean-bremen** [comment]
Ah cool - thanks! While you are at it, you could also replace the GitHub access token with your own - or I could just scrub the automatic check-in stuff and go for manual updates.

**Pull request merged**
