### PR TITLE
W3CTTestRunner: Added a console log at the bottom to avoid annoying m…

### PR DESCRIPTION
**Pull request by Emasoft**
…essage boxes popups and to have a log to copy with a contextual menu to easily report errors.

### CODE REVIEW

**Comment by Emasoft** [comment]
This should be merged with no conflicts.

**Comment by Emasoft** [comment]
Is there any other problem with this?

**Comment by tebjan** [comment]
I am out of office until the 4th October. Will review it when I am back.

**Comment by Emasoft** [comment]
Any update on this?

**Pull request merged**
