### PR TITLE
fix Issue #385 

### PR DESCRIPTION
**Pull request by heindlalex**
Issue #385 : text with "text-anchor=middle" is not on the middle line compared to Chrome
@mrbean-bremen - the text alignment should also work now, please check
Thanks.

### CODE REVIEW

**Comment by heindlalex** [comment]
@mrbean-bremen - Sorry I did not think about that, do you want me to redo the PR from a clean original master branch, or can you cherry pick this time ? Thx.

**Comment by mrbean-bremen** [comment]
I can cherry pick from your branch, but that is not supported by GitHub directly (at least I don't know of it), meaning I would do it from command line, and it would not be your commit, but mine... If that is ok for you...

**Comment by heindlalex** [comment]
ok, for me. Thx.

**Comment by mrbean-bremen** [comment]
Ah, I was wrong - it shows up ok, just never did that.
Thanks for the PR, I'm waiting for the next one :)

**Pull request closed without merging**
