### PR TITLE
Fixing Tiger Test

### PR DESCRIPTION
**Pull request by Shkyrockett**
This reverts the change that broke the Tiger test.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@Shkyrocket: Is this a replacement for my PR? Shall I close it?

**Comment by mrbean-bremen** [comment]
@Shkyrockett :
On a second look, your revert also reverts the very nice performance improvement for path rendering by @LightningDragon. While the call to `PointCount` seems unavoidable, I would keep copying the path points (see #294).

**Comment by tebjan** [comment]
after merging #294 tiger.png seems to work. can you confirm? if yes i'll close this issue.

**Comment by Shkyrockett** [comment]
Yep, the check for whether there are any points seems to mitigate the access violation.

**Pull request closed without merging**
