### PR TITLE
Dispose Matrix in SvgFilter.

### PR DESCRIPTION
**Pull request by H1Gdev**
#### Reference Issue

ref. #641 

#### What does this implement/fix? Explain your changes.

Dispose `Matrix` in SvgFilter and small refactor.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
I think it would be better to first finish #641, which is a larger change, to avoid unneccesary merge conflicts.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

I have confirmed that there are no complex conflicts.
Rather, I would like this PR to be included when testing with PR #641.

By the way, is PR #641 not merged until all filters are implemented ?

**Comment by mrbean-bremen** [comment]
Ok, I let @wieslawsoltes decide that - I will merge if he's ok with that. 

Regarding the merge: I'm all for incremental development, so from my perspective it would be completely ok to merge an unfinished feature as long as it does not break anything (except maybe before a release). 

As long as the PR is flagged as WIP, I consider it not ready for merge. I actually like to use that prefix (in another project, we always prepend a PR with [WIP] as long as it is worked on, and change that to [MRG] if it is ready for review and merge).
I have seen that you have used the "Draft" flag for one of your own PRs, but I think the prefix is more visible.

We may discuss this kind of policy after the repo is moved to the organization...

**Comment by wieslawsoltes** [comment]
You can merge this PR, I will handle merge conflicts in my branch.

**Comment by mrbean-bremen** [comment]
Ok, done - thanks!

**Comment by H1Gdev** [comment]
@mrbean-bremen 
@wieslawsoltes 

Thanks !!

**Pull request merged**
