### PR TITLE
Gdi+ capability check revision

### PR DESCRIPTION
**Pull request by gvheertum**
#### Reference Issue
Following the remarks in #502 by @H1Gdev 

#### What does this implement/fix? Explain your changes.
Added a function to query gdi+ capabilities in the SVGDocument and changed the working of the document load to call an ensure function that will throw the gdi exception instead of having a large try-catch block with multiple exception type queries. The new functions are "tested" in 2 simple unittests that allows developers to check their capabilities by executing the tests.

Also updated the csproj of the SVG project to only include the mac version for the targeted framework (I encoutered some issues with targeting).

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@gvheertum - thanks for the PR! Could you please rebase (or reimplement) your commit to a new branch branched from master? Otherwise it may get complicated with the conflicts...

**Comment by gvheertum** [comment]
I’ll see if I can do this. Still struggling with git sometimes. I did make my own master up to date with your master and branched from there, but now I see it tries to push a whole lot more commits in the PR...

**Comment by mrbean-bremen** [comment]
I usually make a new branch from origin master for each PR, and do not use my own master at all. Or I rebase --hard my own master to origin master and go from there, otherwise all these merge commits get in the way... I could also do the rebasing for you, if you have trouble.

**Comment by mrbean-bremen** [comment]
What I would do in your case: create a new branch from origin master, and cherry-pick the relevant commit there (resolving conflicts if needed).

**Comment by gvheertum** [comment]
Thanks, I sometimes get confused with multiple origins (only used to local and 1 main origin). With your tips I was able to make a new PR (#512) with only the 3 commits that are relevant.

**Pull request closed without merging**
