### PR TITLE
Added handling of invalid color as default color

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- adapted test to check for default value
- see #399

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@gvheertum - can you please review this? This does not fix the actual bug, but the related one with invalid color.

**Comment by gvheertum** [comment]
@mrbean-bremen looks good! Also like what you did with the test to expand the checks performed (not only testing if no error occurs, but also checking the working). The change to the template is also a good one, I never really looked into it in-depth since I was looking for a crash/non-crash scenario and never did a cleaning of the file :)

**Comment by mrbean-bremen** [comment]
Ok, thanks - here comes the second commit :)
This one is smaller...

**Comment by mrbean-bremen** [comment]
@gvheertum - if you are ok with the second commit (which will fix your initial issue) I will merge this.
This is a very small fix, but it took me an hour to get there...

**Comment by gvheertum** [comment]
> Ok, thanks - here comes the second commit :)
> This one is smaller...

Wow... Sometimes it's just "that simple", switching two lines ;) ... Sweet! I kept landing in the Hex parsing, but never was able to pin-point the exact problem. 

Great find! Glad you were able to fix it!

**Comment by mrbean-bremen** [comment]
Ok, thanks - it was easier having your tests in place :) Merging this then..

**Pull request merged**
