### PR TITLE
[WIP] Support for filters

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- preliminary support for feFlood and feBlend primitives
- added support for premultiplied images
- fixed some problems in filter code

Note: this is work in progress and very crude (I have no experience in this field), but any input/review is welcome.
Note that no attempt for optimization has been made.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
I'm going to merge this now before I get more merge conflicts - I may work on this again some time later, a bit short on time right now. At least it doesn't make the current state worse...

**Comment by tebjan** [comment]
you can always merge master into your branch, in order to keep it up to date.

**Comment by mrbean-bremen** [comment]
Yes, you are right - I did this actually several times (force-pushed it), just thought the current state is better than the state before, and as I'm not working on it right now, it would not hurt to merge it. Next time I'll wait...

**Comment by mrbean-bremen** [comment]
Generally, I always prefer rebasing to merging - it makes a cleaner history IMO and avoids these ugly merge commits (there are actually quite a few projects that forbid merge commits for this reason - `django` is one of these I know of). If you have noticed - I always use either rebase or squash commits for merging PRs (depending on the number of commits and the commit comments).

**Comment by mrbean-bremen** [comment]
Ok, I backed out the merge.

**Comment by tebjan** [comment]
did you get master into your branch?

**Comment by mrbean-bremen** [comment]
Yes, I did - otherwise I couldn't have merged. But I agree that the merging was premature, I was just being lazy...

**Pull request merged**
