### PR TITLE
Updates to support multiple dotnet targets

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- support v3.5, v4.0, v4.5.2, v4.7.2 and dotnetcore2.2
- added support for Appveyor build

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
This is the continuation of #415, rebased with current version, fixed some merge errors and problems with excluded code. This is still work in progress.

**Comment by mrbean-bremen** [comment]
@tebjan - this seems to work basically, at least under Windows - for a problem under Linux there is a [separate issue](https://github.com/vvvv/SVG/issues/427). 
I won't wait anymore for the original author for merging - support for Linux and for NetStandard can be added later - but I would like you to check and try this PR to make sure nothing is broken or missing before merging.

**Comment by tebjan** [comment]
looks good to me. i am just wondering why there is the need for so many .net frameworks. since the lowest version will work with any project that targets this or a newer framework.

**Comment by mrbean-bremen** [comment]
Good question - I actually don't know. 
Currently, the unit tests in AppVeyor work only with .NET 4.5 and higher, and in .NETCore, due to the MS test framework, but that is not a real reason...

**Comment by mrbean-bremen** [comment]
Actually, I will just remove the unneeded versions, leaving only .NET 3.5 and .NETCore - you are right, this is not needed, I just hadn't questioned that...

**Comment by mrbean-bremen** [comment]
Ok, I amended the last commit accordingly.

**Comment by tebjan** [comment]
it doesn't hurt either. so, i think you can leave the 4.5 if it helps to have the tests running.

**Comment by mrbean-bremen** [comment]
The tests also run with 3.5 - only the unit test project itself has to be 4.5, so this is not an issue.

**Comment by tebjan** [comment]
ping me if you think it's ready for another nuget release.

**Comment by chucker** [comment]
>This is still work in progress.

> this seems to work basically, at least under Windows

Anything in particular others can help on?

**Comment by mrbean-bremen** [comment]
> Anything in particular others can help on?

Yes - make it work under Linux :)
If have not tested it myself, but there is at least #427 that needs fixing - any help is welcome!

**Comment by chucker** [comment]
I made a pull request for this. Unfortunately, I couldn't figure out how to make a pull request consisting only of my change, so I made it separately at https://github.com/vvvv/SVG/pull/450.

**Comment by mrbean-bremen** [comment]
> I made a pull request for this. Unfortunately, I couldn't figure out how to make a pull request consisting only of my change, so I made it separately at #450.

I should have merged back first... well, I will use yours instead, thanks a lot!

**Comment by mrbean-bremen** [comment]
Closing - will use the new PR instead.

**Pull request closed without merging**
