### PR TITLE
Netcore merge

### PR DESCRIPTION
**Pull request by mrbean-bremen**
This is a cleaned up version of the .NetCore2.2 branch which only contains the new commits.
This is to avoid problems due to different base branches - the relevant commits are cherry-picked and adapted to avoid any conflicts. As far as I can see, this has all needed changes from that branch.

@tebjan - please have a look at the commits (especially yours). If this is ok, we can rebase and merge this.

### CODE REVIEW

**Comment by tebjan** [comment]
this PR has only 8 files changed, while the other one has 18 files changed... can't compare it in detail right now.

**Comment by mrbean-bremen** [comment]
The other changes should have been an artifact due the unneeded netstandard commit - though I can run through them again later today to make sure that they are really not needed.

**Comment by mrbean-bremen** [comment]
Ok, here is a breakdown of the additionally changed files:

Unneeded changes as far as I can see:
- .gitignore - not related to the PR
- SVGViewer/SVGViewer.csproj
- SvgW3CTestRunner/SvgW3CTestRunner.csproj
- SvgW3CTestRunner/app.config 
- SvgW3CTestRunner/Properties/Resources.Designer.cs
- 2 deleted ExCSS Parser files 

Already in master:
- Svg.sln
- SvgDocument.cs
- SvgElementStyle.cs
- LexerIssueTests.cs
- AssemblyInfo.cs (where needed)

**Comment by mrbean-bremen** [comment]
@tebjan - I split of the commits @gvheertum made and merged them to master separately to make things clearer. 
This PR now only contains your commits for automatic git versioning and added authors. The branch name is a bit misleading, as it has nothing to with Netcore (the netcore stuff is already in master). Please check if this can be merged.

**Comment by tebjan** [comment]
thanks for looking into it, yes this can be merged. we could improve the nuget preview version naming, but i can do that after the merge.

**Comment by mrbean-bremen** [comment]
Thanks!

**Pull request merged**
