### PR TITLE
Issue 225 - Image with large embedded image fails to render

### PR DESCRIPTION
**Pull request by AnkHansen**
- Changed SvgImage.Href property from Uri type to String to avoid UriFormatException if Uri contains too much data
- Changed GetImage to receive a string instead of Uri object.
  - Created a temp Uri object in method with substring of allowed length and using this to determine Uri characteristics

### CODE REVIEW

**Comment by tebjan** [comment]
thanks for the effor, especially for also adding a unit test! looks good so far, will check it out and do a quick test soon.

**Comment by AnkHansen** [comment]
Hi Tebjan

We are delivering a new release of our software next week, and I would like to have this fix included.

Are there any changes a new release of SVG will be published within the next week - or should I do a custom build of my own SVG fork for the software I need to ship next week? 

Best regards
/Anders

**Comment by tebjan** [comment]
hello, i'll merge the PR right away... thanks again and sorry for the delay.

**Comment by tebjan** [comment]
published...

**Comment by AnkHansen** [comment]
No problem - thanks for meeting my deadline.. ;-)

**Pull request merged**
