### PR TITLE
Added netstandard2.0 support

### PR DESCRIPTION
**Pull request by wieslawsoltes**
#### Reference Issue

Fixes: #346

#### What does this implement/fix? Explain your changes.

Adds support for targeting netstandard2.0, some code was disabled as its not supported in  netstandard2.0, support should come later in  netstandard2.1.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@wieslawsoltes - thanks for the PR!
@tebjan - what do you think? This has no impact on the other targets, and gets at least some support for Netstandard. The missing color converter stuff will lead to black images in some cases, but it would be a start. I thought that we can wait for Netstandard 2.1 (we discussed this elsewhere), but looking at this PR I'm inclined to merge this. With the .NETCore support in, this is not a big change now.

**Comment by mrbean-bremen** [comment]
@tebjan - any comments?

**Comment by tebjan** [comment]
Looks good, but I wonder whether we can just set up our own color converter and have it completely working and not so many ifdefs. The code of the color converter should be in the . net reference sources.

**Comment by mrbean-bremen** [comment]
Last time I looked it hadn't been there - just the interfaces in netstandard. But that was some time ago, I'll check this again. Generally I agree, of course.

**Comment by mrbean-bremen** [comment]
Actually I'm a bit undecided about this one. According to [this site](https://github.com/dotnet/standard/milestone/3), Netstandard 2.1 is 96% finished, and it looks like it is right around the corner now. Maybe we can just wait this out...

**Comment by mrbean-bremen** [comment]
@wieslawsoltes - I rebased this against master to fix merge conflicts, forgot it is not my own branch...

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes - I rebased this against master to fix merge conflicts, forgot it is not my own branch...

No problem.

**Comment by wieslawsoltes** [comment]
I am also not sure about this, but `.NET Standard 2.1` is also not the best option to wait for. In my software I use `.NET Standard 2.0` as its the best option today.
> Given many of the API additions in .NET Standard 2.1 require runtime changes in order to be meaningful, .NET Framework 4.8 will remain on .NET Standard 2.0 rather than implement .NET Standard 2.1. .NET Core 3.0 as well as upcoming versions of Xamarin, Mono, and Unity will be updated to implement .NET Standard 2.1.

> Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0. In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios. However, this doesn’t mean that library authors cannot take advantage of these APIs even if they have to support .NET Framework. In those cases they can use multi-targeting to compile for both .NET Standard 2.0 as well as .NET Standard 2.1. This allows writing code that can expose more features or provide a more efficient implementation on runtimes that support .NET Standard 2.1 while not giving up on the bigger reach that .NET Standard 2.0 offers.
```
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

**Comment by mrbean-bremen** [comment]
Ok, that sounds convincing. 
There is [code for the color converter](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/ColorConverter.cs) in .NET Core, I'm not sure if we can use it (both technically and legally), but I may have a look at it.
As I understand it, your code does not need the non-implemented stuff to function, right?

**Comment by wieslawsoltes** [comment]
> Ok, that sounds convincing.
> There is [code for the color converter](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/ColorConverter.cs) in .NET Core, I'm not sure if we can use it (both technically and legally), but I may have a look at it.

I think if you leave copyright original headers then it should be possible to use as its MIT licensed but not 100% sure if Ms-PL is compatible with MIT.

> As I understand it, your code does not need the non-implemented stuff to function, right?

I don't think I need this code.

**Comment by mrbean-bremen** [comment]
@tebjan - given the discussion above, I still think it makes sense to merge this as is, and try to implement the missing stuff later. There is obviously a use case for this without the color converter stuff...

**Comment by wieslawsoltes** [comment]
> @tebjan - given the discussion above, I still think it makes sense to merge this as is, and try to implement the missing stuff later. There is obviously a use case for this without the color converter stuff...

I have successfully used the code from this PR in my app using `.NET Core 3.0 preview 6` and `.NET Standard 2.0`. I would vote for merging this PR.

**Comment by wieslawsoltes** [comment]
@mrbean-bremen I am using code from this PR for lat few days without any issues. I vote for merging. You can see working code here: https://github.com/wieslawsoltes/Draw2D/tree/SVG/svg/Svg.Skia

**Comment by mrbean-bremen** [comment]
@tebjan - I really would like to merge this as is - see the previous comments. Regarding the local implementation of the missing functionality - I had looked shortly into this, but I will not be able to put much work into this in the next weeks. Anyway, this can be done later, we just have to clearly state in the release notes that NetStandard is incompletely supported - the main feature for the 3.0 release will be .NET Core support.
Speaking of which - when are you planning to put a release together?

**Comment by tebjan** [comment]
ok, i think this can be merged now, since we have a 3.0 release up with current master.

**Comment by mrbean-bremen** [comment]
Ok, thanks - I'll resolve the conflicts and merge.

**Pull request merged**
