### PR TITLE
Repair calculate a percentage value

### PR DESCRIPTION
**Pull request by NDumper**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Thanks - that looks correct!
Do you have an failing example due to the problem?

**Comment by NDumper** [comment]
You may check it starting this test:

```
        [TestMethod]
        public void TestPercentage()
        {
            var svgDoc = new SvgDocument();
            svgDoc.Width = 200;
            svgDoc.Height = 200;
            var svgEllipse = new SvgEllipseMy()
            {
                ID = "Ellipse",
                CenterX = new SvgUnit(SvgUnitType.Percentage, 50),
                CenterY = new SvgUnit(SvgUnitType.Percentage, 50),
                RadiusX = new SvgUnit(SvgUnitType.Percentage, 15),
                RadiusY = new SvgUnit(SvgUnitType.Percentage, 5),
                Fill = new SvgColourServer(Color.Green),
                Opacity = 1f
            };
            svgDoc.Children.Add(svgEllipse);
            svgDoc.Draw();
            var boudsPref = svgEllipse.Bounds;
            svgDoc.Width = 400;
            svgDoc.Height = 400;
            svgEllipse.InvalidateChildPaths();
            svgDoc.Draw();
            var boundsAfter = svgEllipse.Bounds;
            Assert.AreNotEqual(boudsPref.Size, boundsAfter.Size, "To device value convert error");
        }
```

**Comment by mrbean-bremen** [comment]
Thanks, nice - will you add this to the tests yourself, or shall we do it?

**Comment by NDumper** [comment]
Im adding to the tests.

**Pull request merged**
