### PR TITLE
Added new Draw method

### PR DESCRIPTION
**Pull request by ubbn**
Added new Draw() method that can take raster size and render image in that given size. 
It fixes issues #170 and #169

### CODE REVIEW

**Comment by Sonorpearl** [comment]
HeyHo Mate,

I just included your changes into my Local SVG Version.
And tried: "PictureBox1.Image = svgDoc.Draw(250, 250)"

And sadly nothing has changed. The Picture is still just 60x60, like pre-defined in the SVG and the Predefined Offset within the SVG is still in place.

**Comment by ubbn** [comment]
Hey,

I tested your svg. It works fine by calling svgDoc.Draw(250, 250) which generates attached image in that size. One more thing, your image has colored rectangle size of 60x60. But your whole image is bigger than that. I am afraid you may confuse your whole image with colored rectangle. 


output

**Comment by Sonorpearl** [comment]
Hey ubbn,

the thing is that I have hundreds of SVGs like this. And many SVGs on the Net are made in the same way. And the SVGs work in Environments like Adobe Air or HTML perfectly fine. They do get scaled there to 100% without any adjustments, just passing one width on the container and its done.
SVGs are always scaleable.

**Comment by ubbn** [comment]
One thing I forgot to mention is that this new method Draw(width, height) can calculate scaled size even if you provide one of height or width  as 0. 

About your concern, those tools which you are using presumably do same thing (set height and width). So you can do simple implementation to Resize event of your container to re-render image with new size of your container using the new Draw method.

**Comment by Sonorpearl** [comment]
Ahh okay, thats good to hear.

Do you have any idea on how to solve the Problem, I am facing with the SVG?
I mean how does it break up this Library but its easily done in HTML or Adobe Air?

And one suggestion I want to include is, that the Predefined X/Y of the SVG should be overrided with the svgDoc.X and Y Values. The same way you did with the Width. ^^ That would be very nice.

Thank you for your help and your time, so far.

**Comment by ubbn** [comment]
Hi, I have an idea about how to solve this issue. Probably need to add new issue. But it will take some time to debug & test. 

About your suggestion, I guess once your first problem is fixed, it may not really needed. But I will consider. But I can't promise anything and date.

**Comment by tebjan** [comment]
@ubbn thanks for your commits! have you tested your changes against the svg tester in the Svg.sln?
so that all passing test are still passing?

**Comment by ubbn** [comment]
@tebjan I have tested my all commits on graphics of SVG3WCTestRunner as well as on my own graphics. If you provide instruction to do other detail tests, please let me know.

But about this fix to #171, it overwrites the original size of graphic when no size is given (which fulfills my requirement), but not the size given in < svg > tag which may needed for some other cases. For example in case of graphics of @Sonorpearl. I mean this my commit may not needed to generalize.

**Comment by tebjan** [comment]
good, I'll merge it and check it out...

**Pull request merged**
