### PR TITLE
Update SvgAttributeAttribute.

### PR DESCRIPTION
**Pull request by H1Gdev**
- Change `InAttributeDictionary` default value to `true`.
- Set `InAttributeDictionary` correctly.

### CODE REVIEW

**Comment by H1Gdev** [comment]
ref. #105.

**Comment by H1Gdev** [comment]
In most cases, attribute values are set to `Attributes` property.
So I change `InAttributeDictionary` default value to `true`.

**Comment by mrbean-bremen** [comment]
> In most cases, attribute values are set to Attributes property.

Well, technically true (I checked: 40 vs 31 cases) :)

Is this just a consolidation, or does it fix something?

**Comment by H1Gdev** [comment]
@mrbean-bremen 

Thank you for your review!

> Is this just a consolidation, or does it fix something?

This is just a consolidation.
I did not know what to set in `InAttributeDictionary` property even if I looked at code before...

**Pull request merged**
